FROM node:20-alpine

WORKDIR /app

# Installer les dépendances
COPY package.json package-lock.json ./
RUN npm ci

# Copier le reste du code
COPY . .

EXPOSE 3000

# Mode dev avec hot reload
CMD ["npm", "run", "dev"]
